server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://frontend:80"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true

      # PERFECT FIX: Automatically de-duplicates headers across all services dynamically
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      routes:
        - id: internal-account-service-route
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:8001}
          predicates:
            - Path=/api/v1/internal/**

        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://localhost:8004}
          predicates:
            - Path=/api/v1/auth/**

        - id: users-service-route
          uri: ${USERS_SERVICE_URL:http://localhost:8003}
          predicates:
            - Path=/api/v1/user/**, /api/v1/users/**

        - id: account-service-route
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:8001}
          predicates:
            - Path=/api/v1/account/**, /api/v1/accounts/**

        - id: transactions-service-route
          uri: ${TRANSACTIONS_SERVICE_URL:http://localhost:8002}
          predicates:
            - Path=/api/v1/transactions/**, /api/v1/transaction/**, /api/v1/transaction-logs/**

        - id: aadhar-service-route
          uri: ${AADHAR_SERVICE_URL:http://localhost:8005}
          predicates:
            - Path=/api/v1/verify/**, /api/v1/valid-numbers/**

        - id: company-service-route
          uri: ${COMPANY_SERVICE_URL:http://localhost:8006}
          predicates:
            - Path=/api/v1/company/**

        - id: payment-service-route
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8008}
          predicates:
            - Path=/api/v1/payment/**

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true