server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    # FIX: Disables the version compatibility check completely
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0